// Generated by https://quicktype.io
class Profesor {
  List<Profesores> items = new List();

  Profesor();

  Profesor.fromJsonList(List<dynamic> jsonList) {
    if (jsonList == null) return;

    for (var item in jsonList) {
      final p = new Profesores.fromJsonMap(item);
      items.add(p);
    }
  }
}

class Profesores {
  String usuario;
  String mail;
  String pass;
  String tlfno;
  String dpto;
  String jefatura;
  String tutora;

  Profesores({
    this.usuario,
    this.mail,
    this.pass,
    this.tlfno,
    this.dpto,
    this.jefatura,
    this.tutora,
  });

  Profesores.fromJsonMap(Map<String, dynamic> json) {
    usuario = json['Usuario'];
    mail = json['mail'];
    pass = json['pass'];
    tlfno = json['tlfno'];
    dpto = json['dpto'];
    jefatura = json['jefatura'];
    tutora = json['tutora'];
  }
}
